// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorp0x8ItRG2Nnl86QWO-efJP8d8t-OvA',
    appId: '1:462180809936:web:0c39703249ebe5282132d5',
    messagingSenderId: '462180809936',
    projectId: 'fluttergram-d94a8',
    authDomain: 'fluttergram-d94a8.firebaseapp.com',
    storageBucket: 'fluttergram-d94a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI8ykXvYQLEm4BpO5xZ65b-Zc8bCY7oXQ',
    appId: '1:462180809936:android:7abc280219ce795b2132d5',
    messagingSenderId: '462180809936',
    projectId: 'fluttergram-d94a8',
    storageBucket: 'fluttergram-d94a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ICFhtcXBJu-5BPSTUXqmZ_W0_2x7Zmo',
    appId: '1:462180809936:ios:41252e48b8cf2d0d2132d5',
    messagingSenderId: '462180809936',
    projectId: 'fluttergram-d94a8',
    storageBucket: 'fluttergram-d94a8.appspot.com',
    iosClientId: '462180809936-9jnmcd1a6n0dc0b6ue6naikqhaag6fv6.apps.googleusercontent.com',
    iosBundleId: 'com.hyun.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ICFhtcXBJu-5BPSTUXqmZ_W0_2x7Zmo',
    appId: '1:462180809936:ios:41252e48b8cf2d0d2132d5',
    messagingSenderId: '462180809936',
    projectId: 'fluttergram-d94a8',
    storageBucket: 'fluttergram-d94a8.appspot.com',
    iosClientId: '462180809936-9jnmcd1a6n0dc0b6ue6naikqhaag6fv6.apps.googleusercontent.com',
    iosBundleId: 'com.hyun.instagram',
  );
}
